language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3="dev-master"
    - php: 7.2
      env: TYPO3=^9.0
    - php: 7.2
      env: TYPO3=^8.7
    - php: 7.2
      env: TYPO3=^7.6
    - php: 7.1
      env: TYPO3=^8.7
    - php: 7.1
      env: TYPO3=^7.6
    - php: 7.0
      env: TYPO3=^8.7
    - php: 7.0
      env: TYPO3=^7.6
  allow_failures:
    - env: TYPO3="dev-master"

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require nimut/typo3-complete="$TYPO3"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    echo;
    echo;
    .Build/bin/phpunit -c res/Configuration/UnitTests.xml .Build/Web/typo3conf/ext/testbase/Tests/Unit/;

  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find '.Build/Web/typo3conf/ext/testbase/Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c res/Configuration/FunctionalTests.xml --exclude-group destructive {}';

  - >
    echo;
    echo "Running destructive functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    rm -Rf .Build/Web/typo3temp/*;
    .Build/bin/phpunit -c res/Configuration/FunctionalTests.xml --group destructive .Build/Web/typo3conf/ext/testbase/Tests/Functional/;

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
